[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mint Vinfast", email = "lamviectaivinsmartfuture@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.3.5",
    "sqlmodel>=0.0.42",
    "uvicorn>=0.53.0",
]

[project.scripts]
app = "app.main:app"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
